-- Sample data for local H2 development

-- ENTEMP sample data
INSERT INTO ENTEMP (ROID, SEID, NAME, GRADE, TYPE, ICSACC, BADGE, TITLE, AREACD, PHONE, EXT, EMAIL, POSTYPE, AREA, TOUR, PODIND, TPSIND, CSUIND, AIDEIND, FLEXIND, EACTIVE, UNIX, ELEVEL, PRIMARY_ROID, ORG)
VALUES (25011414, '12345', 'Shannon A Demer', 8, 'R', 'Y', '1234567890', 'Revenue Officer', 214, 4133333, NULL, 'shannon.demer@test.com', '1', 'C', 1, 'N', 'N', 'N', 'N', 'N', 'Y', 'sademe75', 8, 'N', 'CF');

INSERT INTO ENTEMP (ROID, SEID, NAME, GRADE, TYPE, ICSACC, BADGE, TITLE, AREACD, PHONE, EXT, EMAIL, POSTYPE, AREA, TOUR, PODIND, TPSIND, CSUIND, AIDEIND, FLEXIND, EACTIVE, UNIX, ELEVEL, PRIMARY_ROID, ORG)
VALUES (36022414, '12346', 'Wynn H Spinden', 8, 'R', 'Y', '1234567891', 'Revenue Officer', 777, 4133332, NULL, 'wynn.spinden@test.com', '2', 'C', 1, 'N', 'N', 'N', 'N', 'N', 'Y', 'whspin75', 8, 'N', 'CF');

INSERT INTO ENTEMP (ROID, SEID, NAME, GRADE, TYPE, ICSACC, BADGE, TITLE, AREACD, PHONE, EXT, EMAIL, POSTYPE, AREA, TOUR, PODIND, TPSIND, CSUIND, AIDEIND, FLEXIND, EACTIVE, UNIX, ELEVEL, PRIMARY_ROID, ORG)
VALUES (10001001, '123JB', 'John Doe', 13, 'R', 'N', '9876543210', 'Manager', 101, 2345678, NULL, 'john.doe@test.com', '1', 'A', 1, 'N', 'N', 'N', 'N', 'N', 'Y', 'jdoe01', 8, 'N', 'CF');

INSERT INTO ENTEMP (ROID, SEID, NAME, GRADE, TYPE, ICSACC, BADGE, TITLE, AREACD, PHONE, EXT, EMAIL, POSTYPE, AREA, TOUR, PODIND, TPSIND, CSUIND, AIDEIND, FLEXIND, EACTIVE, UNIX, ELEVEL, PRIMARY_ROID, ORG)
VALUES (10001002, '123JB', 'John Doe', 13, 'R', 'N', '9876543211', 'Manager', 101, 2345678, NULL, 'john.doe2@test.com', '1', 'A', 1, 'N', 'N', 'N', 'N', 'N', 'Y', 'jdoe02', 8, 'N', 'AD');

INSERT INTO ENTEMP (ROID, SEID, NAME, GRADE, TYPE, ICSACC, BADGE, TITLE, AREACD, PHONE, EXT, EMAIL, POSTYPE, AREA, TOUR, PODIND, TPSIND, CSUIND, AIDEIND, FLEXIND, EACTIVE, UNIX, ELEVEL, PRIMARY_ROID, ORG)
VALUES (10001003, '123JB', 'John Doe', 13, 'R', 'N', '9876543212', 'Manager', 101, 2345678, NULL, 'john.doe3@test.com', '1', 'A', 1, 'N', 'N', 'N', 'N', 'N', 'Y', 'jdoe03', 8, 'N', 'WI');

INSERT INTO ENTEMP (ROID, SEID, NAME, GRADE, TYPE, ICSACC, BADGE, TITLE, AREACD, PHONE, EXT, EMAIL, POSTYPE, AREA, TOUR, PODIND, TPSIND, CSUIND, AIDEIND, FLEXIND, EACTIVE, UNIX, ELEVEL, PRIMARY_ROID, ORG)
VALUES (10001004, '123JB', 'John Doe', 13, 'R', 'N', '9876543213', 'Manager', 101, 2345678, NULL, 'john.doe4@test.com', '1', 'A', 1, 'N', 'N', 'N', 'N', 'N', 'Y', 'jdoe04', 8, 'N', 'CP');

-- ENTITY_USER sample data (for Last Access Date in Check Employee)
INSERT INTO ENTITY_USER (ENTITY_USER_ID, USER_SEID, USER_NAME, LOGIN_DATE, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER, ISSTAFF, ISLOCKED, PASSWORD, ORG)
VALUES (1, '12345', 'Shannon A Demer', PARSEDATETIME('2025-05-23', 'yyyy-MM-dd'), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'N', 'N', 'ABCDE12345', 'CF');

INSERT INTO ENTITY_USER (ENTITY_USER_ID, USER_SEID, USER_NAME, LOGIN_DATE, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER, ISSTAFF, ISLOCKED, PASSWORD, ORG)
VALUES (2, '12346', 'Wynn H Spinden', PARSEDATETIME('2023-02-14', 'yyyy-MM-dd'), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'N', 'N', 'ABCDE12345', 'CF');

INSERT INTO ENTITY_USER (ENTITY_USER_ID, USER_SEID, USER_NAME, LOGIN_DATE, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER, ISSTAFF, ISLOCKED, PASSWORD, ORG)
VALUES (3, '123JB', 'John Doe', PARSEDATETIME('2026-01-15', 'yyyy-MM-dd'), CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'N', 'N', 'ABCDE12345', 'CF');
